#!/usr/bin/python3
def raise_exception():
    res = 2 + "2"
